codecov:
  token: 5c6372ec-063d-48ff-b4d4-fc43378e9d00
  
# Team Yaml
coverage:
  round: down
  precision: 5

# Repository Yaml
coverage:
  round: up
  range: 0..10

# Used in Codecov after updating
coverage:
  round: up
  range: 0..10
  precision: 5
