- name: Pull Request title rules
  uses: deepakputhraya/action-pr-title@v1.0.0
  with:
    # Regex to validate the pull request title
    regex: # optional, default is .+
    # Comma separated list of prefix allowed to be used in title. eg: feature,hotfix,JIRA-
    allowed_prefixes: # optional, default is 
    # Are the allowed prefixes case sensitive?
    prefix_case_sensitive: # optional
    # Min length of title
    min_length: # optional, default is 1
    # Max length of title. -1 to ignore the rule
    max_length: # optional, default is -1
